### ISSUE TITLE
Runtime crash when using Database.listen()

### ISSUE THREAD

**Issue by shnupta** [fuse-compound/Fuse.Firebase#66]
When using the database module and the listen() my app crashes as soon as I open the page.

Here is my code:
```
var userPath = "clients/users/" + FirebaseUser.uid + "/riders";

Database.listen(userPath);

Database.on('data', function(eventPath, msg) {
	if(eventPath == userPath) 
	{
		reloadRiders();
		console.log("reloading!!!!");
	}
});
```

And the output on the console is:
```
03-18 12:52:06.073 25006 25006 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Set java.util.Map.entrySet()' on a null object reference
03-18 12:52:06.073 25006 25006 E AndroidRuntime: 	at org.json.JSONObject.<init>(JSONObject.java:132)
03-18 12:52:06.073 25006 25006 E AndroidRuntime: 	at com.foreign.Firebase.Database.DatabaseService$1.onDataChange(DatabaseService.java:47)
03-18 12:52:06.073 25006 25006 E AndroidRuntime: 	at com.google.android.gms.internal.zzaih.zza(Unknown Source:13)
03-18 12:52:06.073 25006 25006 E AndroidRuntime: 	at com.google.android.gms.internal.zzajh.zzctc(Unknown Source:2)
03-18 12:52:06.073 25006 25006 E AndroidRuntime: 	at com.google.android.gms.internal.zzajk$1.run(Unknown Source:62)
03-18 12:52:06.073 25006 25006 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:789)
03-18 12:52:06.073 25006 25006 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:98)
03-18 12:52:06.073 25006 25006 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
03-18 12:52:06.073 25006 25006 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6809)
03-18 12:52:06.073 25006 25006 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-18 12:52:06.073 25006 25006 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
03-18 12:52:06.073 25006 25006 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
03-18 12:52:06.075 25006 25006 D AppTracker: App Event: crash
```

#### Relevant code:
[DatabaseService.onDataChanged() - Database.uno#L408](https://github.com/fuse-compound/Fuse.Firebase/blob/85bae19be6216905cb8abedadbee0269f36928c2/src/Firebase.Database/Database.uno#L408)
[Listen() - JS.uno#L272](https://github.com/fuse-compound/Fuse.Firebase/blob/85bae19be6216905cb8abedadbee0269f36928c2/src/Firebase.Database/JS.uno#L272)
[ListenCallback() - JS.uno#L242](https://github.com/fuse-compound/Fuse.Firebase/blob/85bae19be6216905cb8abedadbee0269f36928c2/src/Firebase.Database/JS.uno#L242)

**Comment by shnupta** [comment]
A simple `if (!dataSnapshot.exists()) return;` stops this for now.

**Comment by LuisRodriguezLD** [comment]
this should fix it #68

**Comment by LuisRodriguezLD** [comment]
Just to make sure, did it fix it? Can I close this issue?

**Comment by shnupta** [comment]
Yeah it did. Thanks!:)
